// Should we filter out variables that have not been changed from the text
var filterDefault = false;
// Base file to compile
var baseFile       = 'base.scss';
// Name of the file to customize, this file should exist, however if it is a blank file its content will be populated by variables available in variablesFile
var customizerFile = '_custom.scss';
// Name of the file to get variables information from (leave undefined to get information from the customizer file)
var variablesFile  = 'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_variables.scss';

var otherFiles = [
	'node_modules/bootstrap-sass/assets/stylesheets/_bootstrap.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/_bootstrap-compass.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/_bootstrap-mincer.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/_bootstrap-sprockets.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_alerts.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_badges.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_breadcrumbs.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_button-groups.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_buttons.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_carousel.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_close.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_code.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_component-animations.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_dropdowns.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_forms.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_glyphicons.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_grid.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_input-groups.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_jumbotron.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_labels.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_list-group.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_media.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_mixins.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_modals.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_navbar.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_navs.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_normalize.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_pager.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_pagination.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_panels.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_popovers.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_print.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_progress-bars.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_responsive-embed.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_responsive-utilities.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_scaffolding.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_tables.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_theme.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_thumbnails.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_tooltip.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_type.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_utilities.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_variables.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_wells.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/mixins/_alerts.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/mixins/_background-variant.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/mixins/_border-radius.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/mixins/_buttons.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/mixins/_center-block.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/mixins/_clearfix.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/mixins/_forms.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/mixins/_gradients.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/mixins/_grid-framework.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/mixins/_grid.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/mixins/_hide-text.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/mixins/_image.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/mixins/_labels.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/mixins/_list-group.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/mixins/_nav-divider.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/mixins/_nav-vertical-align.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/mixins/_opacity.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/mixins/_pagination.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/mixins/_panels.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/mixins/_progress-bar.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/mixins/_reset-filter.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/mixins/_reset-text.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/mixins/_resize.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/mixins/_responsive-visibility.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/mixins/_size.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/mixins/_tab-focus.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/mixins/_table-row.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/mixins/_text-emphasis.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/mixins/_text-overflow.scss',
	'node_modules/bootstrap-sass/assets/stylesheets/bootstrap/mixins/_vendor-prefixes.scss',
];
